version: '3.3'
services:
  db:
    image: mongo:4-bionic
    env_file:
      - database.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db
  app:
    build: ./
    env_file:
      - app.env
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
volumes:
    mongo-db: